### ISSUE TITLE
Disable caching in Dropwizard 0.7.1

### ISSUE THREAD

**Issue by explicat** [bazaarvoice/dropwizard-configurable-assets-bundle#34]
Hi,
even though there are already lots of posts around how to disable caching, none of them worked for me.
The static files which I want to serve are located at *src/main/resources/html*. When another file is added to that folder or one file changes, I always need to restart the server in order to see changes.

```java
public void initialize(Bootstrap<LabServerConfiguration> bootstrap) {
        CacheBuilderSpec cacheBuilderSpec = CacheBuilderSpec.disableCaching();
        bootstrap.addBundle(new ConfiguredAssetsBundle("/html", cacheBuilderSpec, "/", "index.html", "Static assets"));
}
```

At first, I did not put anything which would concern assets in the yaml config. It seems like the specification from code is overriden by the configuration in the yaml file in the ConfiguredAssetsBundle's run method, though. As there was nothing specified, the default configuration was taken and maximumSize was set to 100. After appending the following yaml
```yaml
assets:
  cacheSpec: maximumSize=0
```
the debugger reveals that the specified maximumSize is now 0 for sure.

However, behaviour did not change. Can anyone tell me how the assets bundle needs to be configured such that changes come into effect right away?

**Comment by explicat** [comment]
Thanks for the help @amarjeetsingh12 
Unfortunately, the quickfix does not work. Did I miss anything?

```
public class MyConfiguration extends Configuration implements AssetsBundleConfiguration {
    @Valid
    @NotNull
    @JsonProperty
    private DataSourceFactory database = new DataSourceFactory();

    @Valid
    @NotNull
    @JsonProperty
    private final DisableCacheAssetsConfiguration assets = new DisableCacheAssetsConfiguration();
    
    public DataSourceFactory getDatabaseConfiguration() { return database; }

    @Override
    public DisableCacheAssetsConfiguration getAssetsConfiguration() {
        return assets;
    }
}
```


```
public class DisableCacheAssetsConfiguration extends AssetsConfiguration {
    @Override
    public String getCacheSpec() {
        return "maximumWeight=0";
    }
}
```


```
public class Main extends Application<MyConfiguration> {
    //...
    @Override
    public void initialize(Bootstrap<MyConfiguration> bootstrap) {
        CacheBuilderSpec cacheBuilderSpec = CacheBuilderSpec.parse("maximumWeight=0");
        bootstrap.addBundle(new ConfiguredAssetsBundle("/html", cacheBuilderSpec, "/", "index.html", "Static assets"));
    }
}
```

**Comment by amarjeetsingh12** [comment]
@explicat looks like you  everything is fine.You can debug this by checking DisableCacheAssetsConfiguration's getCacheSpec is being called or not If its been called by ConfiguredAssetsBundle it should work.

Further 
com.bazaarvoice.dropwizard.assets.AssetServlet doGet should always say cache size as 0.

Note:Please check your dropwizard-configurable-assets-bundle version

**Comment by nbauernfeind** [comment]
@explicat How are you requesting your pages? How do you know they're being cached? And what layer is caching them?

The assets bundle returns caching headers on every response. Browsers tend to respect these and only asks the server if the hash has changed recently. There actually is some latent bug that I haven't figured out (in years) where files that are requested by javascript do not appear to respect the response's headers. At least, that appears to be the requirement. I see the cache headers that say to revalidate but for some reason the browser doesn't try.

**Comment by nbauernfeind** [comment]
@explicat Also, if setting the cacheSpec is the only thing you do for the assets bundle, then of course you're not seeing fresh content. Depending on how you build or run, the files that are being served are being served from your target directory (or the packaged jar). These things do not change without rebuilding. Additionally, the class loader does not expect or allow content to change -- so as soon as you ask for it it will give you whatever it has.

You need to make sure that you're adding a mapping that points to your local source tree. Something like this might be what you're missing:

```yaml
assets:
  overrides:
    /html: src/main/resources/html/
```

And you actually don't need to disable the the cache in the cachebuilder for this to work.

**Comment by explicat** [comment]
Thanks for your comments!
By stepping through AssetServlet's doGet method as suggested by @amarjeetsingh12, I can see that the local cache's size is 0, even if the html assets are requested several times.
The fact that files which are newly added to the assets folder cannot be requested (404 Not found) also indicate that this is not a problem of caching.

Finally, @nbauernfeind's tip with the overrides in the yaml solved my problem. Thought that the arguments in the configured assets bundle's constructed would be sufficient, but obviously these overrides have to be added. Thank you two a lot!
